### ISSUE TITLE
[Bug]: while importing storefront sdk in an esm enabled module, getting an error

### ISSUE THREAD

**Issue by saishankarmanugula** [getnacelle/nacelle-js#389]
### Project

packages/gatsby-source-nacelle

### Project Version

 "@nacelle/storefront-sdk": "^2.0.0",

### Is this a new issue?

Yes - I've checked the existing Issues, and I'm reporting a new issue.

### What was the expected behavior?

import { StorefrontClient } from '@nacelle/storefront-sdk'; 

Above import should load fine in an esm.js enabled module. We are using esm.js to support es6 modules in the node environment. That is when we are facing with the import. Without esm, it is working fine.

With esm and Storefront sdk version-1 also, everything is working fine

### What happened?

Getting below error during import 

}`}const S={missingEndpoint:"@nacelle/storefront-sdk must be initialized with a 'storefrontEndpoint'.",afterMethodInvalid:n=>T("after","only 
the `query` method and data-fetching methods added by Storefront SDK plugins can be used with the `after` method.",n),afterMethodCallbackIdInvalid:n=>T("after","callback IDs are expected to be strings",n),afterMethodCallbackInvalid:n=>T("after","provided callbacks are expected to be functions or null",n)},J="2.0.1",W=[429,500,502,503,504],N=Q.retryExchange({maxDelayMs:5e3,maxNumberAttempts:5,initialDelayMs:500,retryIf:n=>{if(n.networkError){const e=n.response?.status;return W.includes(e)}else return n.graphQLErrors.some(e=>e.message.includes("INTERNAL_SERVER_ERROR"))}}),P=G({preferGetForPersistedQueries:!0}),A=[N,P,l.fetchExchange];class y{#r;#e;#t;constructor(e){if(!e?.storefrontEndpoint)throw new Error(S.missingEndpoint);this.#e={exchanges:e.exchanges??A,fetchClient:e.fetchClient??globalThis.fetch,storefrontEndpoint:y.getStorefrontEndpoint(e.storefrontEndpoint,e.previewToken),previewToken:e.previewToken,locale:e.locale??"en-US"},this.#r=l.createClient({url:this.#e.storefrontEndpoint,fetch:this.#e.fetchClient,fetchOptions:{headers:y.getHeaders(e.previewToken)},exchanges:this.#e.exchanges}),this.#t={}}getConfig(){const{locale:e,previewToken:t,storefrontEndpoint:r}=this.#e;return{afterSubscriptions:this.#t,locale:e,previewToken:t,storefrontEndpoint:r}}setConfig(e){return this.#e.storefrontEndpoint=y.getStorefrontEndpoint(this.#e.storefrontEndpoint,e.previewToken),typeof e.previewToken<"u"&&(this.#e.previewToken=e.previewToken||void 0),this.#r=l.createClient({url:this.#e.storefrontEndpoint,fetch:this.#e.fetchClient,fetchOptions:{headers:y.getHeaders(e.previewToken)},exchanges:this.#e.exchanges}),{endpoint:this.#e.storefrontEndpoint,previewToken:this.#e.previewToken}}after(e,t,r){if(typeof this[e]>"u")throw new Error(S.afterMethodInvalid(e));if(typeof t>"u"||typeof t!="function"&&t!==null)throw new Error(S.afterMethodCallbackInvalid(t));if(typeof r<"u"&&typeof r!="string")throw new Error(S.afterMethodCallbackIdInvalid(r));let i=this.#t[e];typeof i>"u"&&(i=this.#t[e]={});const s=r??`${e}::${Object.values(i).length}`;typeof t=="function"?i[s]=t:t===null&&delete i[s]}async applyAfter(e,t){const r=this.#t[e];if(typeof r>"u")return t;let i=t;for(const s of Object.values(r))i=await s(i);return i}query({query:e,variables:t}){let r=t;try{typeof t=="string"&&(r=JSON.parse(t))}catch(i){throw new Error(`Could not parse request variables: ${i}`)}return this.#r.query(e,r).toPromise().then(({data:i,error:s})=>{if(s){const a=s.response?.headers?.get("x-amzn-trace-id");a&&(s.message=`${s.message}

                                                                                                                                 ^

SyntaxError: Invalid or unexpected token
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

Node.js v18.16.0

### Link to Reproduction

try importing storfront sdk 2.0 in an esm.js package enabled module

### Node.js Version

18.16.0

### Operating System

Windows

### Relevant log output

```Shell
}`}const S={missingEndpoint:"@nacelle/storefront-sdk must be initialized with a 'storefrontEndpoint'.",afterMethodInvalid:n=>T("after","only 
the `query` method and data-fetching methods added by Storefront SDK plugins can be used with the `after` method.",n),afterMethodCallbackIdInvalid:n=>T("after","callback IDs are expected to be strings",n),afterMethodCallbackInvalid:n=>T("after","provided callbacks are expected to be functions or null",n)},J="2.0.1",W=[429,500,502,503,504],N=Q.retryExchange({maxDelayMs:5e3,maxNumberAttempts:5,initialDelayMs:500,retryIf:n=>{if(n.networkError){const e=n.response?.status;return W.includes(e)}else return n.graphQLErrors.some(e=>e.message.includes("INTERNAL_SERVER_ERROR"))}}),P=G({preferGetForPersistedQueries:!0}),A=[N,P,l.fetchExchange];class y{#r;#e;#t;constructor(e){if(!e?.storefrontEndpoint)throw new Error(S.missingEndpoint);this.#e={exchanges:e.exchanges??A,fetchClient:e.fetchClient??globalThis.fetch,storefrontEndpoint:y.getStorefrontEndpoint(e.storefrontEndpoint,e.previewToken),previewToken:e.previewToken,locale:e.locale??"en-US"},this.#r=l.createClient({url:this.#e.storefrontEndpoint,fetch:this.#e.fetchClient,fetchOptions:{headers:y.getHeaders(e.previewToken)},exchanges:this.#e.exchanges}),this.#t={}}getConfig(){const{locale:e,previewToken:t,storefrontEndpoint:r}=this.#e;return{afterSubscriptions:this.#t,locale:e,previewToken:t,storefrontEndpoint:r}}setConfig(e){return this.#e.storefrontEndpoint=y.getStorefrontEndpoint(this.#e.storefrontEndpoint,e.previewToken),typeof e.previewToken<"u"&&(this.#e.previewToken=e.previewToken||void 0),this.#r=l.createClient({url:this.#e.storefrontEndpoint,fetch:this.#e.fetchClient,fetchOptions:{headers:y.getHeaders(e.previewToken)},exchanges:this.#e.exchanges}),{endpoint:this.#e.storefrontEndpoint,previewToken:this.#e.previewToken}}after(e,t,r){if(typeof this[e]>"u")throw new Error(S.afterMethodInvalid(e));if(typeof t>"u"||typeof t!="function"&&t!==null)throw new Error(S.afterMethodCallbackInvalid(t));if(typeof r<"u"&&typeof r!="string")throw new Error(S.afterMethodCallbackIdInvalid(r));let i=this.#t[e];typeof i>"u"&&(i=this.#t[e]={});const s=r??`${e}::${Object.values(i).length}`;typeof t=="function"?i[s]=t:t===null&&delete i[s]}async applyAfter(e,t){const r=this.#t[e];if(typeof r>"u")return t;let i=t;for(const s of Object.values(r))i=await s(i);return i}query({query:e,variables:t}){let r=t;try{typeof t=="string"&&(r=JSON.parse(t))}catch(i){throw new Error(`Could not parse request variables: ${i}`)}return this.#r.query(e,r).toPromise().then(({data:i,error:s})=>{if(s){const a=s.response?.headers?.get("x-amzn-trace-id");a&&(s.message=`${s.message}



                                                                                                                                 ^

SyntaxError: Invalid or unexpected token
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

Node.js v18.16.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NWRichmond** [comment]
@saishankarmanugula I don't know much about the [`esm` package](https://www.npmjs.com/package/esm), but it looks like it's an old package (last updated 4 years ago). I'm not sure what the issue is, but we will not be pursuing compatibility with the `esm` package, because `@nacelle/storefront-sdk` ships ESM files already to support ESM projects.

As shown in [the `package.json` of `@nacelle/storefront-sdk`], the Storefront SDK ships both ESM and UMD (CommonJS) formats. If your project is [`"type": "module"`](https://nodejs.org/api/packages.html#determining-module-system) or uses a build tool that supports ESM imports, the ESM version will be imported automatically. Otherwise, it will import the UMD version.
